packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  onnxruntime-node: false
  prisma: true
  protobufjs: false
  sharp: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - zod@4.5.4
  - '@aws-sdk/client-s3@3.1123.0'
  - '@aws-sdk/credential-provider-node@3.972.82'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
