import { DatabaseSync } from "node:sqlite";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { MailOutboxEngine, type MailJob } from "./mail-outbox-engine";
import { emailConfigured, runMailOutbox, type MailOutboxAdapter } from "./mail-outbox";
import type { SqlStorage } from "./store-engine";

let db:DatabaseSync, queue:MailOutboxEngine;
const job=():MailJob=>({id:"synthetic-job-000000000001",email:"adult@example.test",purpose:"recovery",token:"a".repeat(64),tokenHash:"synthetic-token-hash",createdAt:Date.now(),expiresAt:Date.now()+900_000,attempts:0});
beforeEach(()=>{db=new DatabaseSync(":memory:");const sql:SqlStorage={exec(query,...values){const rows=db.prepare(query).all(...values) as Record<string,unknown>[];return {toArray:()=>rows};}};queue=new MailOutboxEngine(sql);});
afterEach(()=>{db.close();vi.useRealTimers();});
describe("durable email outbox",()=>{
  it("does not overwrite or extend an idempotent queued request",()=>{const first=job();queue.enqueue(first);expect(queue.enqueue({...first,token:"b".repeat(64)}).duplicate).toBe(true);expect(queue.claim()[0]?.token).toBe(first.token);expect(queue.claim()).toEqual([]);});
  it("leases jobs, bounds retries, and removes sensitive content on exhaustion",()=>{vi.useFakeTimers();queue.enqueue(job());for(let i=1;i<=3;i++){expect(queue.claim()[0]?.attempts).toBe(i);queue.complete(job().id,"retry");vi.advanceTimersByTime(300_000);}expect(queue.status().pending).toBe(0);expect(db.prepare("SELECT * FROM mail_jobs").all()).toEqual([]);});
  it("deletes raw tokens/addresses on provider acceptance, expiry and account deletion",()=>{queue.enqueue(job());queue.complete(job().id,"accepted");expect(queue.status().pending).toBe(0);queue.enqueue({...job(),id:"synthetic-job-000000000002"});queue.purgeByEmail(job().email);expect(queue.status().pending).toBe(0);queue.enqueue({...job(),id:"synthetic-job-000000000003"});queue.cleanup(Date.now()+900_001);expect(db.prepare("SELECT value FROM mail_jobs").all()).toEqual([]);});
  it("does not reuse a completed provider idempotency key with a new undelivered token",()=>{const first=job();queue.enqueue(first);queue.complete(first.id,"accepted");expect(queue.enqueue({...first,token:"b".repeat(64)})).toEqual({queued:true,duplicate:true});expect(queue.claim()).toEqual([]);expect(db.prepare("SELECT * FROM mail_receipts").all()).toEqual([{id:first.id,expires:first.expiresAt}]);queue.cleanup(first.expiresAt+1);expect(db.prepare("SELECT * FROM mail_receipts").all()).toEqual([]);});
  it("fails closed without a verified-provider configuration and HTTPS origin",()=>{expect(emailConfigured({})).toBe(false);expect(emailConfigured({RESEND_API_KEY:"test",EMAIL_FROM:"test@example.test",SITE_ORIGIN:"http://localhost"})).toBe(false);});
  it("uses a stable idempotency key and separates provider acceptance from mailbox delivery",async()=>{
    const pending=job();queue.enqueue(pending);const sent=vi.fn(async()=>new Response("{}",{status:200}));
    const store:MailOutboxAdapter={get:async key=>key.startsWith("email:")?"synthetic-adult":JSON.stringify({email:pending.email}),prepareToken:async()=>true,claim:async()=>queue.claim(Date.now(),1),pending:async id=>queue.pending(id),complete:async(id,status)=>queue.complete(id,status),metric:async()=>{}};
    expect(await runMailOutbox({RESEND_API_KEY:"synthetic-key",EMAIL_FROM:"Mira <test@example.test>",SITE_ORIGIN:"https://mira.example.test"},store,sent)).toEqual({configured:true,accepted:1,failed:0});
    expect(sent).toHaveBeenCalledTimes(1);const args=sent.mock.calls[0] as unknown as [string,RequestInit];expect(new Headers(args[1].headers).get("idempotency-key")).toBe(`mira-recovery-${pending.id}`);expect(queue.status().pending).toBe(0);
  });
  it("does not send when an account disappears or a token was already consumed",async()=>{queue.enqueue(job());const sent=vi.fn(async()=>new Response());const store:MailOutboxAdapter={get:async key=>key.startsWith("email:")?"synthetic-adult":JSON.stringify({email:job().email}),prepareToken:async()=>false,claim:async()=>queue.claim(Date.now(),1),pending:async id=>queue.pending(id),complete:async(id,status)=>queue.complete(id,status),metric:async()=>{}};await runMailOutbox({RESEND_API_KEY:"test",EMAIL_FROM:"test@example.test",SITE_ORIGIN:"https://mira.example.test"},store,sent);expect(sent).not.toHaveBeenCalled();expect(queue.status().pending).toBe(0);});
  it("does not send a queued reset link older than the latest password change",async()=>{const pending=job();queue.enqueue(pending);const sent=vi.fn(async()=>new Response()),prepareToken=vi.fn(async()=>true);const store:MailOutboxAdapter={get:async key=>key.startsWith("email:")?"synthetic-adult":JSON.stringify({email:pending.email,passwordChangedAt:new Date(pending.createdAt+1).toISOString()}),prepareToken,claim:async()=>queue.claim(Date.now(),1),pending:async id=>queue.pending(id),complete:async(id,status)=>queue.complete(id,status),metric:async()=>{}};await runMailOutbox({RESEND_API_KEY:"test",EMAIL_FROM:"test@example.test",SITE_ORIGIN:"https://mira.example.test"},store,sent);expect(sent).not.toHaveBeenCalled();expect(prepareToken).not.toHaveBeenCalled();expect(queue.status().pending).toBe(0);});
});
