import {describe,expect,it,vi} from "vitest";
import {ProviderBackoffError,withProviderDeadline,providerCircuitStatus} from "./provider-resilience";
describe("provider time budgets",()=>{
  it("cancels a hanging adapter immediately when the parent is aborted",async()=>{const controller=new AbortController();const work=vi.fn(()=>new Promise(()=>{}));const task=withProviderDeadline("cloudflare-memory",work,3000,controller.signal);const expected=expect(task).rejects.toMatchObject({name:"AbortError"});controller.abort();await expected;expect(work).toHaveBeenCalledTimes(1);});
  it("never starts a provider after a pre-aborted request",async()=>{const controller=new AbortController();controller.abort();const work=vi.fn(async()=>"bad");await expect(withProviderDeadline("cloudflare",work,100,controller.signal)).rejects.toMatchObject({name:"AbortError"});expect(work).not.toHaveBeenCalled();});
  it("backs off immediately when a provider returns a quota error",async()=>{vi.useFakeTimers();await expect(withProviderDeadline("cloudflare-chat",async()=>{throw new ProviderBackoffError("quota",60);},100)).rejects.toThrow("quota");const work=vi.fn(async()=>"reply");await expect(withProviderDeadline("cloudflare-chat",work,100)).rejects.toThrow("cooling");expect(work).not.toHaveBeenCalled();await vi.advanceTimersByTimeAsync(60001);await expect(withProviderDeadline("cloudflare-chat",work,100)).resolves.toBe("reply");vi.useRealTimers();});
  it("cuts off a hanging provider",async()=>{vi.useFakeTimers();const task=withProviderDeadline("llm7",()=>new Promise(()=>{}),50);const expected=expect(task).rejects.toThrow("deadline");await vi.advanceTimersByTimeAsync(51);await expected;vi.useRealTimers();});
  it("opens after repeated failures and recovers after cooldown",async()=>{vi.useFakeTimers();const fail=vi.fn(async()=>{throw new Error("quota");});for(let i=0;i<3;i++)await expect(withProviderDeadline("inworld-speech",fail,100)).rejects.toThrow();await expect(withProviderDeadline("inworld-speech",fail,100)).rejects.toThrow("cooling");expect(fail).toHaveBeenCalledTimes(3);expect(providerCircuitStatus()["inworld-speech"]?.coolingDown).toBe(true);await vi.advanceTimersByTimeAsync(30001);await expect(withProviderDeadline("inworld-speech",async()=>"audio",100)).resolves.toBe("audio");vi.useRealTimers();});
});
