import { DatabaseSync } from "node:sqlite";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {StoreEngine,type SqlStorage} from "./store-engine";
let db:DatabaseSync,store:StoreEngine;
beforeEach(()=>{db=new DatabaseSync(":memory:");const sql:SqlStorage={exec(query,...values){const statement=db.prepare(query);const rows=statement.all(...values) as Record<string,unknown>[];return{toArray:()=>rows};}};store=new StoreEngine(sql);});
afterEach(()=>{db.close();vi.useRealTimers();});
describe("transactional beta storage",()=>{
  it("migrates records without losing JSON data",()=>{store.put("account:u",JSON.stringify({id:"u",name:"QA"}));expect(JSON.parse(store.get("account:u")!)).toEqual({id:"u",name:"QA"});});
  it("enforces a shared rate window exactly at the limit",()=>{expect(Array.from({length:6},()=>store.rate("chat:client",5,60))).toEqual([false,false,false,false,false,true]);});
  it("expires rate windows",()=>{vi.useFakeTimers();vi.setSystemTime(new Date("2026-09-01T00:00:00Z"));store.rate("voice",1,60);expect(store.rate("voice",1,60)).toBe(true);vi.advanceTimersByTime(60000);expect(store.rate("voice",1,60)).toBe(false);});
  it("retains content-free tombstones after expiry so KV cannot resurrect records",()=>{vi.useFakeTimers();store.put("session:secret",'{"userId":"u","label":"synthetic private"}',1);vi.advanceTimersByTime(2000);store.cleanup();expect(store.get("session:secret")).toBeNull();expect(store.row("session:secret")).toMatchObject({deleted:1,value:null});});
  it("cannot recreate deleted account data with a delayed autosave",()=>{store.put("account:u",'{"id":"u"}');store.remove("account:u");expect(()=>store.put("state:u","private")).toThrow("deleted");expect(()=>store.put("backup:u:today","private")).toThrow("deleted");});
  it("claims email once and allows re-registration only after explicit removal",()=>{expect(store.claimEmail("email:hash",{id:"first"})).toBe(true);expect(store.claimEmail("email:hash",{id:"second"})).toBe(false);store.remove("email:hash");expect(store.claimEmail("email:hash",{id:"third"})).toBe(true);});
  it("paginates without missing or repeating records",()=>{for(let i=0;i<5;i++)store.put(`support:${i}`,"{}");expect(store.list("support:","",2)).toEqual(["support:0","support:1","support:2"]);expect(store.list("support:","support:1",2)).toEqual(["support:2","support:3","support:4"]);});
  it("consumes password recovery only once and invalidates earlier sessions",()=>{store.put("account:u",JSON.stringify({id:"u",passwordHash:"old"}));store.put("recovery:hash",'{"userId":"u"}',900);expect(store.resetPassword("recovery:hash","newhash","salt")).toBe(true);expect(store.resetPassword("recovery:hash","attacker","other")).toBe(false);expect(JSON.parse(store.get("account:u")!)).toMatchObject({passwordHash:"newhash",passwordChangedAt:expect.any(String)});});
  it("rejects other previously issued recovery links after a password reset",()=>{store.put("account:u",'{"id":"u","passwordHash":"old"}');const createdAt=Date.now()-60_000;store.put("recovery:a",JSON.stringify({userId:"u",createdAt}),900);store.put("recovery:b",JSON.stringify({userId:"u",createdAt}),900);expect(store.resetPassword("recovery:a","newhash","salt")).toBe(true);expect(store.resetPassword("recovery:b","attacker","other")).toBe(false);expect(store.get("recovery:b")).toBeNull();expect(JSON.parse(store.get("account:u")!).passwordHash).toBe("newhash");});
  it("ignores duplicate and older billing events; never reactivates from a duplicate",()=>{store.put("account:u",'{"id":"u"}');store.billing("e1","u","2026-09-01T12:00:00Z",{status:"active"});store.billing("e2","u","2026-09-01T13:00:00Z",{status:"cancelled"});store.billing("e1","u","2026-09-01T14:00:00Z",{status:"active"});store.billing("e0","u","2026-09-01T11:00:00Z",{status:"active"});expect(JSON.parse(store.get("billing:u")!).status).toBe("cancelled");});
  it("does not apply billing events after account deletion",()=>{store.remove("account:u");store.billing("e1","u","2026-09-01T12:00:00Z",{status:"active"});expect(store.get("billing:u")).toBeNull();});
  it("erases sessions, recovery, billing and snapshots atomically and queues legacy purge",()=>{store.put("account:u",'{"id":"u"}');store.put("state:u","private");store.put("backup:u:2026-09-01","private");store.put("session:token",'{"userId":"u"}');store.put("recovery:token",'{"userId":"u"}');store.put("billing:u",'{"status":"active"}');store.eraseAccount("u","email",[]);for(const key of ["account:u","state:u","backup:u:2026-09-01","session:token","recovery:token","billing:u"])expect(store.get(key)).toBeNull();expect(store.list("purge:").length).toBeGreaterThan(5);expect(()=>store.put("state:u","late save")).toThrow();});
  it("aggregates only event counts and latency, not content",()=>{store.metric("api:chat",false,300);store.metric("api:chat",true,500);expect(store.metrics()[0]).toMatchObject({total:2,failures:1,averageLatencyMs:400});});
  it("measures a rolling 15-minute latency histogram and expires old incidents",()=>{vi.useFakeTimers();for(let i=0;i<19;i++)store.metric("api:chat",false,900);store.metric("api:chat",true,7000);expect(store.recentMetrics()[0]).toMatchObject({total:20,failures:1,p50UpperBoundMs:1000,p95UpperBoundMs:1000,p99UpperBoundMs:8000,maxLatencyMs:7000});vi.advanceTimersByTime(16*60000);expect(store.recentMetrics()).toEqual([]);expect(store.metrics()).toHaveLength(1);});
});

describe("storage mutation failure boundaries",()=>{
 it("rejects missing accounts, stale revisions and missing memory targets without writing",async()=>{const {freshDemo}=await import("./demo-storage");const state=freshDemo();state.user.id="u";state.user.adultConfirmed=true;state.memoryEnabled=true;const policy={aiProcessingConsent:true,memoryEnabled:true,conversationStorageEnabled:true};expect(store.readAccountState("missing")).toBeNull();expect(store.transcriptSearch("missing",{query:"tea"})).toEqual({messages:[]});expect(store.transcriptContext("missing","x")).toEqual({messages:[]});expect(store.memoryCommand("missing",{action:"forget",id:"m"},1)).toEqual({missing:true});expect(store.conversationCommand("missing",{action:"create"},1)).toEqual({missing:true});expect(store.acceptPolicy("missing",policy,1)).toEqual({missing:true});store.bootstrap("email:u",{id:"u"},state,"session:u","{}",60,NaN);expect(store.transcriptContext("u","missing")).toEqual({messages:[]});for(const result of [store.memoryCommand("u",{action:"forget",id:"m"},0),store.conversationCommand("u",{action:"create"},0),store.acceptPolicy("u",policy,0)])expect(result).toMatchObject({conflict:true,revision:1});expect(store.memoryCommand("u",{action:"forget",id:"missing"},1)).toEqual({notFound:true});});
 it("handles missing and changed owners for recovery and email verification",()=>{expect(store.verifyEmail("missing")).toBe(false);store.put("verification:orphan",JSON.stringify({userId:"none",email:"qa@example.test"}));expect(store.verifyEmail("verification:orphan")).toBe(false);store.put("account:u",JSON.stringify({id:"u",email:"new@example.test"}));store.put("verification:changed",JSON.stringify({userId:"u",email:"old@example.test"}));expect(store.verifyEmail("verification:changed")).toBe(false);store.put("recovery:orphan",JSON.stringify({userId:"none"}));expect(store.resetPassword("recovery:orphan","new","salt")).toBe(false);store.metric("very-slow",true,20000);expect(store.recentMetrics()[0]).toMatchObject({p50UpperBoundMs:120000,p95UpperBoundMs:120000,p99UpperBoundMs:120000});});
 it("applies memory capacity and pin-only edits while retaining normalized content",async()=>{const {freshDemo}=await import("./demo-storage");const state=freshDemo();state.user.id="u";state.user.adultConfirmed=true;state.memoryEnabled=true;store.bootstrap("email:u",{id:"u"},state,"session:u","{}",60);const first=store.memoryCommand("u",{action:"create",content:"Likes tea"},1);if(!("state"in first))throw Error("fixture");const id=first.state.memories[0]!.id;const pinned=store.memoryCommand("u",{action:"edit",id,pinned:true},2);expect(pinned).toMatchObject({state:{memories:[{id,pinned:true,content:"Likes tea"}]}});const record=store.readAccountState("u")!;record.state.memories=Array.from({length:300},(_,i)=>({...first.state.memories[0]!,id:`m${i}`}));store.put("state:u",JSON.stringify(record));expect(store.memoryCommand("u",{action:"create",content:"One too many"},record.revision)).toEqual({limit:true});});
});
