"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, ShieldCheck } from "lucide-react";
import { BrandMark } from "./BrandMark";

export function AuthRecovery({ mode }: { mode: "forgot" | "reset" | "verify" }) {
  const [complete, setComplete] = useState(false);
  const copy = mode === "forgot" ? { eyebrow: "Account recovery", title: "Reset your password.", detail: "We’ll create a mock recovery link without revealing whether an account exists.", action: "Send reset link" } : mode === "reset" ? { eyebrow: "Choose a new password", title: "Make it memorable to you.", detail: "The mock reset token is accepted locally; production mode uses a short-lived, single-use token.", action: "Update password" } : { eyebrow: "Email verification", title: "Confirm it’s you.", detail: "Use the verification token from your local mock flow.", action: "Verify email" };
  return <main className="auth-page"><section className="auth-panel"><Link href="/"><BrandMark /></Link><span className="eyebrow">{copy.eyebrow}</span><h1>{copy.title}</h1><p>{copy.detail}</p>{complete ? <div className="auth-success" role="status"><CheckCircle2 aria-hidden="true" /><div><strong>{mode === "forgot" ? "Recovery link created" : mode === "reset" ? "Password updated" : "Email verified"}</strong><span>You can continue safely in the local demo.</span></div></div> : <form onSubmit={(event) => { event.preventDefault(); setComplete(true); }}>{mode === "forgot" ? <label className="field">Email<input type="email" autoComplete="email" required placeholder="you@example.com" /></label> : null}{mode === "reset" ? <><label className="field">Reset token<input required minLength={8} defaultValue="reset.local-demo-token" /></label><label className="field">New password<input type="password" autoComplete="new-password" required minLength={8} placeholder="At least 8 characters" /></label></> : null}{mode === "verify" ? <label className="field">Verification token<input required minLength={8} defaultValue="verify.local-demo-token" /></label> : null}<button type="submit" className="button button--primary">{copy.action} <ArrowRight aria-hidden="true" /></button></form>}<small><ShieldCheck aria-hidden="true" /> Tokens and passwords are never included in app logs.</small><Link href="/login"><ArrowLeft aria-hidden="true" /> Back to login</Link></section><aside className="auth-visual" aria-label="Luma in the moonlit companion room" /></main>;
}
