import Link from "next/link";
import { ArrowRight, BellRing, BookHeart, Bot, Camera, Check, HeartHandshake, LockKeyhole, Mic, ShieldCheck, Sparkles } from "lucide-react";
import { BrandMark } from "./BrandMark";

export function MarketingPage() {
  return (
    <main className="marketing">
      <header className="marketing-header"><Link href="/" aria-label="Mira home"><BrandMark /></Link><nav aria-label="Public navigation"><Link href="/features">Features</Link><Link href="/memory">Memory</Link><Link href="/voice">Voice</Link><Link href="/safety">Safety</Link><Link href="/pricing">Pricing</Link></nav><div><Link className="button button--ghost" href="/login">Log in</Link><Link className="button button--primary" href="/demo">Meet Mira</Link></div></header>
      <section className="marketing-hero">
        <div className="marketing-hero__scene" />
        <div className="marketing-hero__veil" />
        <div className="marketing-hero__copy"><span className="eyebrow">Free public beta · AI companion · Adults 18+</span><h1>She sees you. She hears you. She remembers.</h1><p>Step into Mira’s world—then chat in English or Hinglish, talk hands-free, share avatar calls, and return to a relationship with continuity.</p><div><Link className="button button--primary" href="/demo">Start free beta <ArrowRight aria-hidden="true" /></Link><Link className="button button--glass" href="#memory">See how memory works</Link></div><small><ShieldCheck aria-hidden="true" /> Clearly AI · No payment required · Memory you control</small></div>
      </section>

      <section className="marketing-strip" aria-label="Product commitments"><span>Avatar-led presence</span><span>Voice and video calls</span><span>Inspect every memory</span><span>Human relationships still matter</span></section>

      <section className="marketing-section marketing-section--split" id="memory"><div><span className="eyebrow">An AI that remembers your life</span><h2>Not everything. The right things.</h2><p>Mira turns important moments into memory candidates, shows where they came from, and lets you correct, pin, pause, or forget them.</p><ul className="check-list"><li><Check aria-hidden="true" /> Facts, preferences, people, goals, and shared moments</li><li><Check aria-hidden="true" /> Contradiction handling instead of competing “truths”</li><li><Check aria-hidden="true" /> Token-aware retrieval that only uses relevant context</li></ul><Link href="/memory">Explore the memory system <ArrowRight aria-hidden="true" /></Link></div><div className="memory-demo"><BookHeart aria-hidden="true" /><span>Memory from tonight</span><p>Asha has an interview tomorrow at eleven.</p><small>Source: conversation · High confidence</small><div aria-label="Available memory controls"><span>Correct</span><span>Pin</span><span>Forget</span></div></div></section>

      <section className="marketing-section"><div className="section-intro"><span className="eyebrow">More than text</span><h2>Talk in the way the moment needs.</h2><p>Text, voice, and avatar calls share the same conversation context. Voice availability depends on browser microphone permission and free-beta provider capacity.</p></div><div className="feature-trio"><article><Mic aria-hidden="true" /><h3>Hands-free voice</h3><p>Automatic listening, transcription, and spoken replies keep the conversation moving.</p></article><article><Camera aria-hidden="true" /><h3>Camera only when visible</h3><p>Explicit permission, obvious indicators, and no background recording.</p></article><article><Sparkles aria-hidden="true" /><h3>An expressive original avatar</h3><p>Stable live expressions and lip movement give calls a visual presence without copying a character.</p></article></div></section>

      <section className="marketing-section marketing-section--tint"><div className="section-intro"><span className="eyebrow">Built for flourishing</span><h2>A companion should widen your world.</h2><p>Helpful prompts can lead back to a friend, a walk, a goal, or a conversation you have been avoiding. The product never claims you only need it.</p></div><div className="flourish-grid"><span><HeartHandshake aria-hidden="true" /> “Want to message Alex?”</span><span><BellRing aria-hidden="true" /> “How did the interview go?”</span><span><Bot aria-hidden="true" /> “Nice to see you again.”</span></div></section>

      <section className="marketing-section"><div className="section-intro"><span className="eyebrow">Privacy is a feature</span><h2>Your life is not ad inventory.</h2></div><div className="privacy-band"><LockKeyhole aria-hidden="true" /><div><h3>Designed around your control</h3><p>No conversation content in generic analytics. Clear memory, export, and account-deletion controls. Beta conversations can be processed by the configured AI and speech providers.</p></div><Link className="button button--ghost" href="/privacy">Read the privacy approach</Link></div></section>

      <section className="marketing-section"><div className="section-intro"><span className="eyebrow">Free public beta</span><h2>Meet Mira without a paywall.</h2><p>The launch beta is free and does not ask for payment. Text, voice, avatar calls, activities, and inspectable memory are available while capacity lasts.</p></div><div className="pricing-grid pricing-grid--beta"><article className="pricing-card--featured"><span>Available now</span><h3>Public beta</h3><strong>₹0</strong><p>No card required. Help shape conversation quality, voice, memory, and the launch experience.</p><Link className="button button--primary" href="/demo">Start free beta</Link></article><article><span className="eyebrow">What to expect</span><h3>Beta boundaries</h3><ul className="check-list"><li><Check aria-hidden="true" /> Adults 18+ only</li><li><Check aria-hidden="true" /> Not therapy or emergency care</li><li><Check aria-hidden="true" /> Avoid sensitive or regulated information</li><li><Check aria-hidden="true" /> Features may change as feedback arrives</li></ul><Link className="button button--ghost" href="/support">Share feedback</Link></article></div></section>

      <section className="marketing-section marketing-faq"><div className="section-intro"><span className="eyebrow">Straight answers</span><h2>Trust should not hide in fine print.</h2></div><details open><summary>Is Mira a real person?</summary><p>No. Mira is an AI product and remains clearly disclosed as AI.</p></details><details><summary>Does it remember everything?</summary><p>No. It extracts a small set of useful candidates and keeps them inspectable.</p></details><details><summary>Is this therapy?</summary><p>No. It is for everyday supportive conversation, not diagnosis, treatment, or emergency care.</p></details><details><summary>Do I need to pay?</summary><p>No. This launch is a free public beta and does not ask for payment details.</p></details></section>

      <section className="marketing-cta"><div><span className="eyebrow">Start with what’s real today</span><h2>Meet a companion who feels present.</h2><p>No perfect prompt. No pressure to perform.</p><Link className="button button--primary" href="/demo">Meet Mira <ArrowRight aria-hidden="true" /></Link></div><img src="/assets/mira/portrait.png" alt="Mira, an original AI companion avatar" /></section>

      <footer className="marketing-footer"><div><BrandMark /><p>An original AI companion centered on presence, voice, memory, and shared moments.</p><small>Free public beta · AI companion · Adults 18+ · Not therapy or emergency care</small></div><div><strong>Product</strong><Link href="/features">Features</Link><Link href="/memory">Memory</Link><Link href="/voice">Voice</Link><Link href="/pricing">Pricing</Link></div><div><strong>Trust</strong><Link href="/safety">Safety</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/support">Support</Link></div><div><strong>Account</strong><Link href="/login">Log in</Link><Link href="/signup">Sign up</Link><Link href="/demo">Open demo</Link></div></footer>
    </main>
  );
}
