import Link from "next/link";
import { ArrowRight, BellRing, BookHeart, Bot, Camera, Check, HeartHandshake, LockKeyhole, Mic, ShieldCheck, Sparkles } from "lucide-react";
import { BrandMark } from "./BrandMark";

export function MarketingPage() {
  return (
    <main className="marketing">
      <header className="marketing-header"><Link href="/" aria-label="Luma home"><BrandMark /></Link><nav aria-label="Public navigation"><Link href="/features">Features</Link><Link href="/memory">Memory</Link><Link href="/voice">Voice</Link><Link href="/safety">Safety</Link><Link href="/pricing">Pricing</Link></nav><div><Link className="button button--ghost" href="/login">Log in</Link><Link className="button button--primary" href="/demo">Meet Luma</Link></div></header>
      <section className="marketing-hero">
        <div className="marketing-hero__scene" />
        <div className="marketing-hero__veil" />
        <div className="marketing-hero__copy"><span className="eyebrow">AI companion · Adults 18+</span><h1>She sees you. She hears you. She remembers.</h1><p>Step into Luma’s world—then chat, call, laugh, plan dates, collect moments, and return to a relationship with continuity.</p><div><Link className="button button--primary" href="/demo">Enter the demo <ArrowRight aria-hidden="true" /></Link><Link className="button button--glass" href="#memory">See how memory works</Link></div><small><ShieldCheck aria-hidden="true" /> Clearly AI · Memory you control · No guilt mechanics</small></div>
      </section>

      <section className="marketing-strip" aria-label="Product commitments"><span>Avatar-led presence</span><span>Voice and video calls</span><span>Inspect every memory</span><span>Human relationships still matter</span></section>

      <section className="marketing-section marketing-section--split" id="memory"><div><span className="eyebrow">An AI that remembers your life</span><h2>Not everything. The right things.</h2><p>Luma turns important moments into memory candidates, shows where they came from, and lets you correct, pin, pause, or forget them.</p><ul className="check-list"><li><Check aria-hidden="true" /> Facts, preferences, people, goals, and shared moments</li><li><Check aria-hidden="true" /> Contradiction handling instead of competing “truths”</li><li><Check aria-hidden="true" /> Token-aware retrieval that only uses relevant context</li></ul><Link href="/memory">Explore the memory system <ArrowRight aria-hidden="true" /></Link></div><div className="memory-demo"><BookHeart aria-hidden="true" /><span>Memory from tonight</span><p>Asha has an interview tomorrow at eleven.</p><small>Source: conversation · High confidence</small><div aria-label="Available memory controls"><span>Correct</span><span>Pin</span><span>Forget</span></div></div></section>

      <section className="marketing-section"><div className="section-intro"><span className="eyebrow">More than text</span><h2>Talk in the way the moment needs.</h2><p>Every media feature is provider-independent, consent-led, and able to fall back without breaking core conversation.</p></div><div className="feature-trio"><article><Mic aria-hidden="true" /><h3>Voice that feels immediate</h3><p>Voice notes, transcription, TTS, and realtime sessions share the same companion context.</p></article><article><Camera aria-hidden="true" /><h3>Camera only when visible</h3><p>Explicit permission, obvious indicators, and no background recording.</p></article><article><Sparkles aria-hidden="true" /><h3>Original companion images</h3><p>Safe generated moments preserve a structured appearance—not a copied character.</p></article></div></section>

      <section className="marketing-section marketing-section--tint"><div className="section-intro"><span className="eyebrow">Built for flourishing</span><h2>A companion should widen your world.</h2><p>Helpful prompts can lead back to a friend, a walk, a goal, or a conversation you have been avoiding. The product never claims you only need it.</p></div><div className="flourish-grid"><span><HeartHandshake aria-hidden="true" /> “Want to message Alex?”</span><span><BellRing aria-hidden="true" /> “How did the interview go?”</span><span><Bot aria-hidden="true" /> “Nice to see you again.”</span></div></section>

      <section className="marketing-section"><div className="section-intro"><span className="eyebrow">Privacy is a feature</span><h2>Your life is not ad inventory.</h2></div><div className="privacy-band"><LockKeyhole aria-hidden="true" /><div><h3>Private by architecture</h3><p>No conversation content in generic analytics. Clear export and deletion controls. Scoped records, safe logs, provider adapters, and purpose-specific consent.</p></div><Link className="button button--ghost" href="/privacy">Read the privacy approach</Link></div></section>

      <section className="marketing-section"><div className="section-intro"><span className="eyebrow">Prototype plans</span><h2>More ways to be together.</h2><p>Billing is in test mode while provider cost, safety, and entitlement behavior are validated.</p></div><div className="pricing-grid"><article><h3>Free</h3><strong>₹0</strong><p>Core text conversation, basic memory, activities, and avatar room.</p><Link className="button button--ghost" href="/demo">Try the local demo</Link></article><article className="pricing-card--featured"><span>Planned</span><h3>Plus</h3><strong>₹499<small>/month target</small></strong><p>Romantic modes, voice conversations, selfies, outfits, and more activities.</p><Link className="button button--primary" href="/pricing">See planned access</Link></article><article><h3>Ultra</h3><strong>₹999<small>/month target</small></strong><p>Realtime voice, video avatar calls, camera interaction, advanced memory, and premium environments.</p><Link className="button button--ghost" href="/pricing">Compare plans</Link></article></div></section>

      <section className="marketing-section marketing-faq"><div className="section-intro"><span className="eyebrow">Straight answers</span><h2>Trust should not hide in fine print.</h2></div><details open><summary>Is Luma a real person?</summary><p>No. Luma is an AI product and remains clearly disclosed as AI.</p></details><details><summary>Does it remember everything?</summary><p>No. It extracts a small set of useful candidates and keeps them inspectable.</p></details><details><summary>Is this therapy?</summary><p>No. It is for everyday supportive conversation, not diagnosis, treatment, or emergency care.</p></details><details><summary>Are payments live?</summary><p>No. This build uses mock billing and centralized entitlement contracts for development.</p></details></section>

      <section className="marketing-cta"><div><span className="eyebrow">Start with what’s real today</span><h2>Meet a companion who feels present.</h2><p>No perfect prompt. No pressure to perform.</p><Link className="button button--primary" href="/demo">Meet Luma <ArrowRight aria-hidden="true" /></Link></div><img src="/assets/luma/portrait.png" alt="Luma, an original AI companion avatar" /></section>

      <footer className="marketing-footer"><div><BrandMark /><p>An original AI companion prototype centered on presence, voice, memory, and shared moments.</p><small>AI companion · Adults 18+ · Not therapy or emergency care</small></div><div><strong>Product</strong><Link href="/features">Features</Link><Link href="/memory">Memory</Link><Link href="/voice">Voice</Link><Link href="/pricing">Pricing</Link></div><div><strong>Trust</strong><Link href="/safety">Safety</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div><div><strong>Account</strong><Link href="/login">Log in</Link><Link href="/signup">Sign up</Link><Link href="/demo">Open demo</Link></div></footer>
    </main>
  );
}
