"use client";

import { useState } from "react";
import { BellRing, BookHeart, BrainCircuit, CalendarDays, Check, CreditCard, Database, Download, FileJson, Heart, LogOut, Moon, ShieldCheck, Sparkles, Sun, Trash2, UserRound, UsersRound, Volume2 } from "lucide-react";
import type { DemoState } from "@/lib/state";
import { Modal } from "./Modal";

export function ProfileView({ state, liveMode = false, onChange, onExport, onDelete, onLogout, onUpgrade, onOpenMemory, onOpenActivities }: { state: DemoState; liveMode?: boolean; onChange: (next: DemoState) => void; onExport: () => void | Promise<void>; onDelete: () => void | Promise<void>; onLogout?: () => void | Promise<void>; onUpgrade: () => void; onOpenMemory: () => void; onOpenActivities: () => void }) {
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [confirmation, setConfirmation] = useState("");
  const relationshipMemory = state.memories.find((memory) => memory.status === "active" && memory.type === "relationship");
  const companionSince = new Date(state.companion.createdAt).toLocaleDateString(undefined, { month: "long", year: "numeric" });
  return (
    <section className="workspace profile-view" aria-labelledby="profile-title">
      <header className="workspace-header workspace-header--text"><div><span className="eyebrow">Your story</span><h1 id="profile-title">You</h1><p>What {state.companion.name} knows, how your relationship feels, and the boundaries you control.</p></div><div className="profile-summary"><img src="/assets/luma/portrait.png" alt="" /><span><strong>{state.user.name}</strong><small>With {state.companion.name} since {companionSince}</small></span></div></header>
      <div className="settings-grid">
        <section className="settings-section"><div className="settings-section__heading"><UserRound aria-hidden="true" /><div><h2>Account</h2><p>Basic profile information</p></div></div><label className="field">Name<input value={state.user.name} onChange={(event) => onChange({ ...state, user: { ...state.user, name: event.target.value } })} /></label><label className="field">Pronouns<select value={state.user.pronouns} onChange={(event) => onChange({ ...state, user: { ...state.user, pronouns: event.target.value as DemoState["user"]["pronouns"] } })}><option>she/her</option><option>he/him</option><option>they/them</option></select></label></section>

        <section className="settings-section subscription-card"><div className="settings-section__heading"><CreditCard aria-hidden="true" /><div><h2>{state.subscription.planId === "free" ? "Free plan" : `${state.subscription.planId[0]?.toUpperCase()}${state.subscription.planId.slice(1)} plan`}</h2><p>{state.subscription.testMode ? "Billing runs in safe test mode" : "Subscription managed securely"}</p></div></div><p>Text chat, avatar, inspectable memory, and activities are always available.</p><button type="button" className="button button--primary" onClick={onUpgrade}><Sparkles aria-hidden="true" /> Compare all plans</button></section>

        <section className="settings-section"><div className="settings-section__heading"><BrainCircuit aria-hidden="true" /><div><h2>Response style</h2><p>Teach {state.companion.name} how support should feel</p></div></div><label className="toggle-line"><span><strong>Listen before advising</strong><small>Ask before moving into solutions.</small></span><input type="checkbox" checked={state.responsePreferences.listeningFirst} onChange={(event) => onChange({ ...state, responsePreferences: { ...state.responsePreferences, listeningFirst: event.target.checked } })} /></label><label className="field">Response length<select value={state.responsePreferences.responseLength} onChange={(event) => onChange({ ...state, responsePreferences: { ...state.responsePreferences, responseLength: event.target.value as DemoState["responsePreferences"]["responseLength"] } })}><option value="short">Short</option><option value="balanced">Balanced</option><option value="deep">Deep</option></select></label><label className="field">Questions<select value={state.responsePreferences.questionFrequency} onChange={(event) => onChange({ ...state, responsePreferences: { ...state.responsePreferences, questionFrequency: event.target.value as DemoState["responsePreferences"]["questionFrequency"] } })}><option value="balanced">Only when useful</option><option value="rare">Rarely ask me questions</option></select></label><label className="field">Advice style<select value={state.responsePreferences.adviceStyle} onChange={(event) => onChange({ ...state, responsePreferences: { ...state.responsePreferences, adviceStyle: event.target.value as DemoState["responsePreferences"]["adviceStyle"] } })}><option value="ask-first">Ask first</option><option value="gentle">Gentle suggestions</option><option value="direct">Direct and practical</option></select></label></section>

        <section className="settings-section settings-section--wide relationship-settings"><div className="settings-section__heading"><Heart aria-hidden="true" /><div><h2>Relationship & chemistry</h2><p>Warmth and romance are always your choice. Adult modes require explicit opt-in.</p></div></div><div className="relationship-slider-grid">{(["friendliness", "affection", "flirtiness", "playfulness", "romance", "sensuality", "humor", "initiative"] as const).map((trait) => <label key={trait}><span>{trait[0]?.toUpperCase()}{trait.slice(1)} <strong>{state.relationship[trait]}</strong></span><input type="range" min="0" max="100" value={state.relationship[trait]} disabled={trait === "sensuality" && !state.relationship.sensualOptIn} onChange={(event) => onChange({ ...state, relationship: { ...state.relationship, [trait]: Number(event.target.value) } })} /></label>)}</div><div className="relationship-consent"><label className="toggle-line"><span><strong>Romantic mode</strong><small>Affectionate and playful, with healthy boundaries.</small></span><input type="checkbox" checked={state.relationship.romanticOptIn} onChange={(event) => onChange({ ...state, relationship: { ...state.relationship, romanticOptIn: event.target.checked, romance: event.target.checked ? Math.max(40, state.relationship.romance) : 0 } })} /></label><label className="toggle-line"><span><strong>Sensual / flirty mode</strong><small>Adults 18+ only. Changes tone, never your safety controls.</small></span><input type="checkbox" checked={state.relationship.sensualOptIn} onChange={(event) => onChange({ ...state, relationship: { ...state.relationship, sensualOptIn: event.target.checked, sensuality: event.target.checked ? 25 : 0 } })} /></label></div></section>

        <section className="settings-section"><div className="settings-section__heading"><UsersRound aria-hidden="true" /><div><h2>Important people</h2><p>Relationship memory you can inspect</p></div></div>{relationshipMemory ? <div className="person-memory"><span>{relationshipMemory.content.trim().charAt(0).toUpperCase()}</span><div><strong>From your shared memory</strong><small>{relationshipMemory.content}</small></div></div> : <p className="settings-note">No people saved yet. You decide what becomes a memory.</p>}<button type="button" className="button button--ghost" onClick={onOpenMemory}><BookHeart aria-hidden="true" /> See everything {state.companion.name} remembers</button></section>

        <section className="settings-section"><div className="settings-section__heading"><CalendarDays aria-hidden="true" /><div><h2>Upcoming</h2><p>Events, journal, and quiet-hour follow-ups</p></div></div>{state.futureEvents.length ? state.futureEvents.slice(0, 2).map((event) => <div className="upcoming-row" key={event.id}><span><strong>{event.description}</strong><small>{new Date(event.eventDate).toLocaleString()}</small></span></div>) : <p className="settings-note">Nothing planned yet. Add something you want {state.companion.name} to remember.</p>}<button type="button" className="button button--ghost" onClick={onOpenActivities}><Sparkles aria-hidden="true" /> Plan something together</button></section>

        <section className="settings-section"><div className="settings-section__heading"><BellRing aria-hidden="true" /><div><h2>Follow-ups & calls</h2><p>Opt-in planning and quiet boundaries</p></div></div><label className="field">Message frequency<select value={state.notifications.frequency} onChange={(event) => onChange({ ...state, notifications: { ...state.notifications, frequency: event.target.value as DemoState["notifications"]["frequency"] } })}><option value="off">Off</option><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label><label className="field">Incoming AI calls<select value={state.proactiveCalls} onChange={(event) => onChange({ ...state, proactiveCalls: event.target.value as DemoState["proactiveCalls"] })}><option value="never">Never</option><option value="rarely">Rarely</option><option value="sometimes">Sometimes</option><option value="often">Often</option></select></label><div className="form-grid"><label className="field">Quiet from<input type="time" value={state.notifications.quietStart} onChange={(event) => onChange({ ...state, notifications: { ...state.notifications, quietStart: event.target.value } })} /></label><label className="field">Until<input type="time" value={state.notifications.quietEnd} onChange={(event) => onChange({ ...state, notifications: { ...state.notifications, quietEnd: event.target.value } })} /></label></div><p className="settings-note"><ShieldCheck aria-hidden="true" /> {liveMode ? "Your account preferences respect these quiet hours." : "Mock mode plans interactions locally and sends nothing."}</p></section>

        <section className="settings-section"><div className="settings-section__heading"><Database aria-hidden="true" /><div><h2>Memory & privacy</h2><p>Control the continuity layer</p></div></div><label className="toggle-line"><span><strong>Use approved memories</strong><small>New suggestions remain inspectable.</small></span><input type="checkbox" checked={state.memoryEnabled} onChange={(event) => onChange({ ...state, memoryEnabled: event.target.checked })} /></label><button type="button" className="button button--ghost" onClick={onOpenMemory}><BookHeart aria-hidden="true" /> Inspect {state.memories.filter((memory) => memory.status === "active").length} memories</button><label className="toggle-line"><span><strong>AI-processing consent</strong><small>{liveMode ? "Required only while you use AI features." : "Mock mode keeps processing on this device."}</small></span><input type="checkbox" checked={state.aiProcessingConsent} onChange={(event) => onChange({ ...state, aiProcessingConsent: event.target.checked })} /></label><label className="toggle-line"><span><strong>{liveMode ? "Server conversation history" : "Store conversation history"}</strong><small>{liveMode ? "Delete the current transcript from Chat tools, or delete the account below." : "When off, messages are omitted from browser storage."}</small></span><input type="checkbox" checked={liveMode ? true : state.conversationStorageEnabled} disabled={liveMode} onChange={(event) => onChange({ ...state, conversationStorageEnabled: event.target.checked })} /></label></section>

        <section className="settings-section"><div className="settings-section__heading"><Volume2 aria-hidden="true" /><div><h2>Appearance</h2><p>Choose a comfortable surface</p></div></div><div className="theme-choice"><button type="button" className={state.theme === "light" ? "theme-button theme-button--active" : "theme-button"} onClick={() => onChange({ ...state, theme: "light" })}><Sun aria-hidden="true" /> Light {state.theme === "light" ? <Check aria-hidden="true" /> : null}</button><button type="button" className={state.theme === "dark" ? "theme-button theme-button--active" : "theme-button"} onClick={() => onChange({ ...state, theme: "dark" })}><Moon aria-hidden="true" /> Dark {state.theme === "dark" ? <Check aria-hidden="true" /> : null}</button></div></section>

        <section className="settings-section settings-section--wide"><div className="settings-section__heading"><FileJson aria-hidden="true" /><div><h2>Your data</h2><p>Portable, inspectable, and deletable</p></div></div><div className="data-actions"><div><Download aria-hidden="true" /><span><strong>{liveMode ? "Export account data" : "Export local demo"}</strong><small>Download profile, conversation, memory, and preference data as JSON.</small></span><button type="button" className="button button--ghost" onClick={() => void onExport()}>Export</button></div>{liveMode && onLogout ? <div><LogOut aria-hidden="true" /><span><strong>Sign out</strong><small>End this session without removing your account.</small></span><button type="button" className="button button--ghost" onClick={() => void onLogout()}>Sign out</button></div> : null}<div className="danger-row"><Trash2 aria-hidden="true" /><span><strong>{liveMode ? "Delete account" : "Delete local demo data"}</strong><small>{liveMode ? "Permanently removes the account and companion data." : "This permanently clears the current browser profile."}</small></span><button type="button" className="button button--danger" onClick={() => setDeleteOpen(true)}>Delete</button></div></div></section>
      </div>

      {deleteOpen ? <Modal title={liveMode ? "Delete your account?" : "Delete this Luma demo?"} description="This clears conversations, memories, preferences, and companion setup. It cannot be undone." onClose={() => setDeleteOpen(false)}><label className="field">Type DELETE to confirm<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label><div className="modal-actions"><button type="button" className="button button--ghost" onClick={() => setDeleteOpen(false)}>Cancel</button><button type="button" className="button button--danger" disabled={confirmation !== "DELETE"} onClick={() => void onDelete()}><Trash2 aria-hidden="true" /> Permanently delete</button></div></Modal> : null}
    </section>
  );
}
