"use client";

import { useState } from "react";
import { BellRing, BookHeart, BrainCircuit, CalendarDays, Check, CreditCard, Database, Download, FileJson, Heart, Moon, ShieldCheck, Sparkles, Sun, Trash2, UserRound, UsersRound, Volume2 } from "lucide-react";
import type { DemoState } from "@/lib/state";
import { Modal } from "./Modal";

export function ProfileView({ state, onChange, onExport, onDelete, onUpgrade, onOpenMemory, onOpenActivities }: { state: DemoState; onChange: (next: DemoState) => void; onExport: () => void; onDelete: () => void; onUpgrade: () => void; onOpenMemory: () => void; onOpenActivities: () => void }) {
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [confirmation, setConfirmation] = useState("");
  return (
    <section className="workspace profile-view" aria-labelledby="profile-title">
      <header className="workspace-header workspace-header--text"><div><span className="eyebrow">Your story</span><h1 id="profile-title">You</h1><p>What Luma knows, how your relationship feels, and the boundaries you control.</p></div><div className="profile-summary"><img src="/assets/luma/portrait.png" alt="" /><span><strong>{state.user.name}</strong><small>With {state.companion.name} since July 2026</small></span></div></header>
      <div className="settings-grid">
        <section className="settings-section"><div className="settings-section__heading"><UserRound aria-hidden="true" /><div><h2>Account</h2><p>Basic profile information</p></div></div><label className="field">Name<input value={state.user.name} onChange={(event) => onChange({ ...state, user: { ...state.user, name: event.target.value } })} /></label><label className="field">Pronouns<select value={state.user.pronouns} onChange={(event) => onChange({ ...state, user: { ...state.user, pronouns: event.target.value as DemoState["user"]["pronouns"] } })}><option>she/her</option><option>he/him</option><option>they/them</option></select></label></section>

        <section className="settings-section subscription-card"><div className="settings-section__heading"><CreditCard aria-hidden="true" /><div><h2>{state.subscription.planId === "free" ? "Free plan" : `${state.subscription.planId[0]?.toUpperCase()}${state.subscription.planId.slice(1)} plan`}</h2><p>{state.subscription.testMode ? "Billing runs in safe test mode" : "Subscription managed securely"}</p></div></div><p>Text chat, avatar, inspectable memory, and activities are always available.</p><button type="button" className="button button--primary" onClick={onUpgrade}><Sparkles aria-hidden="true" /> Compare all plans</button></section>

        <section className="settings-section"><div className="settings-section__heading"><BrainCircuit aria-hidden="true" /><div><h2>Response style</h2><p>Teach Luma how support should feel</p></div></div><label className="toggle-line"><span><strong>Listen before advising</strong><small>Ask before moving into solutions.</small></span><input type="checkbox" checked={state.responsePreferences.listeningFirst} onChange={(event) => onChange({ ...state, responsePreferences: { ...state.responsePreferences, listeningFirst: event.target.checked } })} /></label><label className="field">Response length<select value={state.responsePreferences.responseLength} onChange={(event) => onChange({ ...state, responsePreferences: { ...state.responsePreferences, responseLength: event.target.value as DemoState["responsePreferences"]["responseLength"] } })}><option value="short">Short</option><option value="balanced">Balanced</option><option value="deep">Deep</option></select></label><label className="field">Questions<select value={state.responsePreferences.questionFrequency} onChange={(event) => onChange({ ...state, responsePreferences: { ...state.responsePreferences, questionFrequency: event.target.value as DemoState["responsePreferences"]["questionFrequency"] } })}><option value="balanced">Only when useful</option><option value="rare">Rarely ask me questions</option></select></label><label className="field">Advice style<select value={state.responsePreferences.adviceStyle} onChange={(event) => onChange({ ...state, responsePreferences: { ...state.responsePreferences, adviceStyle: event.target.value as DemoState["responsePreferences"]["adviceStyle"] } })}><option value="ask-first">Ask first</option><option value="gentle">Gentle suggestions</option><option value="direct">Direct and practical</option></select></label></section>

        <section className="settings-section settings-section--wide relationship-settings"><div className="settings-section__heading"><Heart aria-hidden="true" /><div><h2>Relationship & chemistry</h2><p>Warmth and romance are always your choice. Adult modes require explicit opt-in.</p></div></div><div className="relationship-slider-grid">{(["friendliness", "affection", "flirtiness", "playfulness", "romance", "sensuality", "humor", "initiative"] as const).map((trait) => <label key={trait}><span>{trait[0]?.toUpperCase()}{trait.slice(1)} <strong>{state.relationship[trait]}</strong></span><input type="range" min="0" max="100" value={state.relationship[trait]} disabled={trait === "sensuality" && !state.relationship.sensualOptIn} onChange={(event) => onChange({ ...state, relationship: { ...state.relationship, [trait]: Number(event.target.value) } })} /></label>)}</div><div className="relationship-consent"><label className="toggle-line"><span><strong>Romantic mode</strong><small>Affectionate and playful, with healthy boundaries.</small></span><input type="checkbox" checked={state.relationship.romanticOptIn} onChange={(event) => onChange({ ...state, relationship: { ...state.relationship, romanticOptIn: event.target.checked, romance: event.target.checked ? Math.max(40, state.relationship.romance) : 0 } })} /></label><label className="toggle-line"><span><strong>Sensual / flirty mode</strong><small>Adults 18+ only. Changes tone, never your safety controls.</small></span><input type="checkbox" checked={state.relationship.sensualOptIn} onChange={(event) => onChange({ ...state, relationship: { ...state.relationship, sensualOptIn: event.target.checked, sensuality: event.target.checked ? 25 : 0 } })} /></label></div></section>

        <section className="settings-section"><div className="settings-section__heading"><UsersRound aria-hidden="true" /><div><h2>Important people</h2><p>Relationship memory you can inspect</p></div></div><div className="person-memory"><span>A</span><div><strong>Aman</strong><small>Best friend · Bengaluru · last discussed 3 days ago</small></div></div><button type="button" className="button button--ghost" onClick={onOpenMemory}><BookHeart aria-hidden="true" /> See everything Luma remembers</button></section>

        <section className="settings-section"><div className="settings-section__heading"><CalendarDays aria-hidden="true" /><div><h2>Upcoming</h2><p>Events, journal, and quiet-hour follow-ups</p></div></div>{state.futureEvents.slice(0, 2).map((event) => <div className="upcoming-row" key={event.id}><span><strong>{event.description}</strong><small>{new Date(event.eventDate).toLocaleString()}</small></span></div>)}<button type="button" className="button button--ghost" onClick={onOpenActivities}><Sparkles aria-hidden="true" /> Plan something together</button></section>

        <section className="settings-section"><div className="settings-section__heading"><BellRing aria-hidden="true" /><div><h2>Follow-ups & calls</h2><p>Opt-in planning and quiet boundaries</p></div></div><label className="field">Message frequency<select value={state.notifications.frequency} onChange={(event) => onChange({ ...state, notifications: { ...state.notifications, frequency: event.target.value as DemoState["notifications"]["frequency"] } })}><option value="off">Off</option><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label><label className="field">Incoming AI calls<select value={state.proactiveCalls} onChange={(event) => onChange({ ...state, proactiveCalls: event.target.value as DemoState["proactiveCalls"] })}><option value="never">Never</option><option value="rarely">Rarely</option><option value="sometimes">Sometimes</option><option value="often">Often</option></select></label><div className="form-grid"><label className="field">Quiet from<input type="time" value={state.notifications.quietStart} onChange={(event) => onChange({ ...state, notifications: { ...state.notifications, quietStart: event.target.value } })} /></label><label className="field">Until<input type="time" value={state.notifications.quietEnd} onChange={(event) => onChange({ ...state, notifications: { ...state.notifications, quietEnd: event.target.value } })} /></label></div><p className="settings-note"><ShieldCheck aria-hidden="true" /> Mock mode plans interactions locally and sends nothing.</p></section>

        <section className="settings-section"><div className="settings-section__heading"><Database aria-hidden="true" /><div><h2>Memory & privacy</h2><p>Control the continuity layer</p></div></div><label className="toggle-line"><span><strong>Use approved memories</strong><small>New suggestions remain inspectable.</small></span><input type="checkbox" checked={state.memoryEnabled} onChange={(event) => onChange({ ...state, memoryEnabled: event.target.checked })} /></label><button type="button" className="button button--ghost" onClick={onOpenMemory}><BookHeart aria-hidden="true" /> Inspect {state.memories.filter((memory) => memory.status === "active").length} memories</button><label className="toggle-line"><span><strong>AI-processing consent</strong><small>Mock mode keeps processing on this device.</small></span><input type="checkbox" defaultChecked /></label><label className="toggle-line"><span><strong>Conversation storage</strong><small>Required for continuity in this local demo.</small></span><input type="checkbox" defaultChecked /></label></section>

        <section className="settings-section"><div className="settings-section__heading"><Volume2 aria-hidden="true" /><div><h2>Appearance</h2><p>Choose a comfortable surface</p></div></div><div className="theme-choice"><button type="button" className={state.theme === "light" ? "theme-button theme-button--active" : "theme-button"} onClick={() => onChange({ ...state, theme: "light" })}><Sun aria-hidden="true" /> Light {state.theme === "light" ? <Check aria-hidden="true" /> : null}</button><button type="button" className={state.theme === "dark" ? "theme-button theme-button--active" : "theme-button"} onClick={() => onChange({ ...state, theme: "dark" })}><Moon aria-hidden="true" /> Dark {state.theme === "dark" ? <Check aria-hidden="true" /> : null}</button></div></section>

        <section className="settings-section settings-section--wide"><div className="settings-section__heading"><FileJson aria-hidden="true" /><div><h2>Your data</h2><p>Portable, inspectable, and deletable</p></div></div><div className="data-actions"><div><Download aria-hidden="true" /><span><strong>Export local demo</strong><small>Download profile, conversation, memory, and preference data as JSON.</small></span><button type="button" className="button button--ghost" onClick={onExport}>Export</button></div><div className="danger-row"><Trash2 aria-hidden="true" /><span><strong>Delete local demo data</strong><small>This permanently clears the current browser profile.</small></span><button type="button" className="button button--danger" onClick={() => setDeleteOpen(true)}>Delete</button></div></div></section>
      </div>

      {deleteOpen ? <Modal title="Delete this Luma demo?" description="This clears local conversations, memories, preferences, and companion setup. It cannot be undone." onClose={() => setDeleteOpen(false)}><label className="field">Type DELETE to confirm<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label><div className="modal-actions"><button type="button" className="button button--ghost" onClick={() => setDeleteOpen(false)}>Cancel</button><button type="button" className="button button--danger" disabled={confirmation !== "DELETE"} onClick={onDelete}><Trash2 aria-hidden="true" /> Permanently delete</button></div></Modal> : null}
    </section>
  );
}
