import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, ShieldCheck } from "lucide-react";
import { BrandMark } from "./BrandMark";

const content = {
  features: { eyebrow: "Product", title: "A companion shaped by continuity.", intro: "Conversation, memory, personality, relationship state, voice, activities, and healthy follow-up share one context engine.", points: ["Streaming conversation with deterministic mock mode", "Multiple inspectable memory types", "Original avatar room and customization catalog", "Voice, vision, and media provider interfaces", "Activities, journal, future events, and opt-in nudges"] },
  memory: { eyebrow: "Memory", title: "Remember fewer things correctly.", intro: "Candidates are scored, deduplicated, checked for contradictions, embedded, and retrieved within a strict context budget.", points: ["Semantic, episodic, preference, relationship, goal, emotional, and shared memories", "Source message links and confidence", "Edit, pin, search, pause, and delete", "Hybrid relevance, recency, importance, and relationship ranking", "Conversation, daily, and weekly summary architecture"] },
  voice: { eyebrow: "Voice", title: "The same companion, spoken aloud.", intro: "Voice notes and realtime calls use the same approved memory and safety context as text chat.", points: ["STT and TTS provider adapters", "Realtime session abstraction with barge-in architecture", "Visible microphone and camera states", "Transcript and audio metadata separation", "Mock sessions that work without external keys"] },
  safety: { eyebrow: "Safety", title: "Support without pretending to be care.", intro: "Mira is not a clinician, crisis service, or replacement for human relationships.", points: ["Input and output safety layers", "Crisis responses with India-specific Tele-MANAS routing", "No guilt, jealousy, exclusivity, or fake sentience", "Romantic features gated behind adult policy", "Content-minimized safety event logging"] },
  pricing: { eyebrow: "Pricing", title: "Entitlements, not scattered paywalls.", intro: "FREE, PLUS, ULTRA, and PLATINUM are centrally configured. Billing remains in test mode in this build.", points: ["Server-authoritative feature checks", "Stripe-ready web adapter", "RevenueCat-compatible mobile boundary", "Webhook reconciliation and idempotency contracts", "No emotional support locked behind engagement grinding"] },
  privacy: { eyebrow: "Privacy", title: "Private by default, controllable in product.", intro: "Production launch remains gated on verified identity, processor contracts, scoped encryption, deletion evidence, and independent review.", points: ["No raw private chat in generic logs or analytics", "Purpose-specific consent and clear indicators", "Inspectable memory and data export", "Account and memory deletion controls", "Tenant-scoped repository contracts"] },
  terms: { eyebrow: "Terms", title: "Prototype terms, plainly stated.", intro: "This local build is for evaluation with non-sensitive content. It is not a healthcare product, emergency service, or live paid service.", points: ["Adults 18+ only", "Original product and licensed assets only", "No illegal, abusive, or exploitative use", "Mock providers may return deterministic content", "Production terms require legal approval before launch"] },
} as const;

export function PublicInfoPage({ slug }: { slug: keyof typeof content }) {
  const page = content[slug];
  return <main className="public-page"><header className="public-header"><Link href="/"><BrandMark /></Link><Link href="/app" className="button button--primary">Open app <ArrowRight aria-hidden="true" /></Link></header><section className="public-hero"><span className="eyebrow">{page.eyebrow}</span><h1>{page.title}</h1><p>{page.intro}</p><ul>{page.points.map((point) => <li key={point}><Check aria-hidden="true" /> {point}</li>)}</ul><div className="trust-note"><ShieldCheck aria-hidden="true" /> Original prototype · AI disclosed · Adults 18+</div><Link href="/" className="back-link"><ArrowLeft aria-hidden="true" /> Back home</Link></section></main>;
}
