import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, ShieldCheck } from "lucide-react";
import { BrandMark } from "./BrandMark";
import { SupportForm } from "./SupportForm";

const content = {
  features: { eyebrow: "Product", title: "A companion shaped by continuity.", intro: "Conversation, memory, personality, relationship state, voice, activities, and healthy follow-up share one context engine.", points: ["Context-aware multilingual conversation", "Multiple inspectable memory types", "Original avatar room and customization catalog", "Voice, camera, and generated-media controls", "Activities, journal, future events, and opt-in nudges"] },
  memory: { eyebrow: "Memory", title: "Remember fewer things correctly.", intro: "Candidates are scored, deduplicated, checked for contradictions, embedded, and retrieved within a strict context budget.", points: ["Semantic, episodic, preference, relationship, goal, emotional, and shared memories", "Source message links and confidence", "Edit, pin, search, pause, and delete", "Hybrid relevance, recency, importance, and relationship ranking", "Conversation, daily, and weekly summary architecture"] },
  voice: { eyebrow: "Voice", title: "The same companion, spoken aloud.", intro: "Voice notes and realtime calls use the same approved memory and safety context as text chat.", points: ["STT and TTS provider adapters", "Realtime session abstraction with barge-in architecture", "Visible microphone and camera states", "Transcript and audio metadata separation", "Mock sessions that work without external keys"] },
  safety: { eyebrow: "Safety", title: "Support without pretending to be care.", intro: "Mira is not a clinician, crisis service, or replacement for human relationships.", points: ["Input and output safety layers", "Crisis responses with India-specific Tele-MANAS routing", "No guilt, jealousy, exclusivity, or fake sentience", "Romantic features gated behind adult policy", "Content-minimized safety event logging"] },
  pricing: { eyebrow: "Free public beta", title: "Meet Mira without a paywall.", intro: "The launch beta costs ₹0 and does not request a card. Text, hands-free voice, avatar calls, activities, and inspectable memory are available while beta capacity lasts.", points: ["No payment details required", "Adults 18+ only", "Beta features and providers may change", "Fair-use and capacity limits can apply", "No emotional support locked behind engagement grinding"] },
  privacy: { eyebrow: "Privacy", title: "Your controls, clearly scoped.", intro: "This public beta stores account state on Cloudflare and can send conversations or audio to the configured AI and speech providers. Please avoid sensitive or regulated information while the beta is under review.", points: ["No raw private chat in generic analytics", "Visible microphone and camera permission states", "Inspectable, editable, and forgettable memory", "Account export and deletion controls", "Provider and retention details documented in product"] },
  terms: { eyebrow: "Terms", title: "Public beta terms, plainly stated.", intro: "Mira is an experimental adults-only AI companion. It is not a healthcare product, emergency service, or paid service, and responses may be incomplete or wrong.", points: ["Adults 18+ only", "Original product and licensed assets only", "No illegal, abusive, or exploitative use", "Do not rely on Mira for medical, legal, financial, or emergency decisions", "Features may change or be unavailable during the beta"] },
  support: { eyebrow: "Support", title: "Tell us what needs attention.", intro: "Use the public issue tracker for product bugs and beta feedback. Do not include conversation text, account credentials, personal data, or other sensitive information in a report.", points: ["Include the page and browser you used", "Describe what you expected and what happened", "Add a screenshot only after removing personal details", "Never share passwords, tokens, or private conversations", "Urgent or emergency help is outside this product"] },
} as const;

export function PublicInfoPage({ slug }: { slug: keyof typeof content }) {
  const page = content[slug];
  return <main className="public-page"><header className="public-header"><Link href="/"><BrandMark /></Link><Link href="/demo" className="button button--primary">Start free beta <ArrowRight aria-hidden="true" /></Link></header><section className="public-hero"><span className="eyebrow">{page.eyebrow}</span><h1>{page.title}</h1><p>{page.intro}</p><ul>{page.points.map((point) => <li key={point}><Check aria-hidden="true" /> {point}</li>)}</ul>{slug === "support" ? <SupportForm /> : null}<div className="trust-note"><ShieldCheck aria-hidden="true" /> Original product · AI disclosed · Adults 18+</div><Link href="/" className="back-link"><ArrowLeft aria-hidden="true" /> Back home</Link></section></main>;
}
